name: Satubinha First Pipeline

on:
  push:
    branches: [ main ]
  
jobs:
  test-pipeline:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd

      - name: List files in the directory
        run: ls -la

      - name: Show date and time
        run: date

      - name: Show user information
        run: whoami

      - name: Show docker version
        run: docker --version 

      - name: Print a message
        run: echo "Pipeline do Satubinha funcionando!"