name: Terraform Staging 

on:
  workflow_dispatch:
    inputs:
      approve_apply:
        description: 'Aprovar apply se houver mudanças?'
        required: true
        default: 'no'

jobs:
  terraform-staging:
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true

    defaults:
      run:
        working-directory: environments/staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Write SSH public key to file
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > id_ed25519.pub

      - name: Show Terraform version  
        run: terraform version

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=staging.tfvars -out=tfplan

      - name: Show Terraform Plan
        run: terraform show -no-color tfplan

      - name: Terraform Apply Condicional
        if: ${{ github.event.inputs.approve_apply == 'yes' }}
        run: terraform apply -auto-approve tfplan

<<<<<<< HEAD
      - name: Terraform Apply
        if: success()
        run: |
          terraform show -json tfplan | jq '.resource_changes | length' > changes.txt
          CHANGES=$(cat changes.txt)
          if [ "$CHANGES" -gt 0 ]; then
            terraform apply -auto-approve tfplan
          else
            echo "Sem mudanças no plan. Apply não necessário."
          fi
=======
      - name: Abort Apply
        if: ${{ github.event.inputs.approve_apply != 'yes' }}
        run: echo "Apply não aprovado. Workflow interrompido." && exit 1
>>>>>>> 961d662 (adicionar aprovação interativa no workflow de Staging)

      - name: Show Terraform Output
        run: terraform output
