name: Terraform Dev Apply Workflow

on:
  workflow_dispatch:
    apply:
      description: 'Executar terraform apply?'
      required: false
      default: 'true'
    plan_destroy:
      description: 'Executar terraform plan para destroy?'
      required: false
      default: 'false'
    destroy:
      description: 'Executar terraform destroy?'
      required: false
      default: 'false'

jobs:
  terraform-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Write SSH public key to file
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > id_ed25519.pub

      - name: Show Terraform version  
        run: terraform version

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Conditional Terraform Apply
        if: ${{ github.event.inputs.apply == 'true' }}
        run: |
          echo "Executando terraform apply..."
          terraform show -json tfplan | jq '.resource_changes | length' > changes.txt
          CHANGES=$(cat changes.txt)
          if [ "$CHANGES" -gt 0 ]; then
            terraform apply -auto-approve tfplan
          else
            echo "Sem mudanças no plan. Apply não necessário."
          fi

      - name: Conditional Terraform Plan Destroy
        if: ${{ github.event.inputs.plan_destroy == 'true' }}
        run: |
          echo "Executando terraform plan para destroy..."
          terraform plan -destroy -var-file=dev.tfvars -out=tfplan_destroy
          terraform show -no-color tfplan_destroy

      - name: Conditional Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'true' }}
        run: |
          echo "Executando terraform destroy..."
          terraform destroy -auto-approve -var-file=dev.tfvars 

      - name: Show terraform output
        run: terraform output 